### ISSUE TITLE
Refactor: combine two tools into one

### ISSUE THREAD

**Issue by CheyenneSlager** [MahmoudRe/JetBrainsPlugin#21]
The Kotlin and Java compatible tools need to be combined into one. Very long methods should also be splitted up into smaller ones. All code should be clean and provided with comments when needed.

**Comment by MahmoudRe** [comment]
This issue is done and the associated branch has been merged!

**Comment by MahmoudRe** [comment]
This issue is done and the associated branch has been merged!
